spring:
  application:
    name: turbine-service

server:
  port: 8061

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

turbine:
  app-config: service-consumer
  cluster-name-expression: new String("default")
  combine-host-port: true
