spring:
  application:
    name: service-gateway

server:
  port: 9000

zuul:
  routes:
    service-producer:
      path: /service-producer/**
      url: http://localhost:8011/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
